### ISSUE TITLE
[Acceptance tester] Add command birthday format  

### ISSUE THREAD

**Issue by aungmyin23** [CS2103AUG2017-W14-B2/main#119]
![image](https://user-images.githubusercontent.com/31042213/32363007-0982618e-c0a8-11e7-9049-de2616937a17.png)

As seen from the picture, the birthday format is incomplete in the Example that shows to the user.

**Comment by hengyu95** [comment]
Fixed!

**Comment by aungmyin23** [comment]
Alright! I will close this issue then! Thanks!
