### ISSUE TITLE
[Acceptance tester] Filter command  

### ISSUE THREAD

**Issue by aungmyin23** [CS2103AUG2017-W14-B2/main#121]
![image](https://user-images.githubusercontent.com/31042213/32363436-571bd270-c0aa-11e7-8c8c-add743a0076c.png)

As seen from the picture above the filter command doesn't display the person with name 'Alex' instead it list everyone in the contact list instead.

![image](https://user-images.githubusercontent.com/31042213/32363603-28e1ea38-c0ab-11e7-94c1-36eb91335865.png)

Under user guide the 'filter' command is not included under the summary table.

**Comment by awarenessxz** [comment]
This command have been removed! Thank you.
