### ISSUE TITLE
Enhancement for Add Command

### ISSUE THREAD

**Issue by wenzongteo** [CS2103AUG2017-W14-B2/main#24]
Currently, the add command will add a `-` string value to an optional attribute when the optional attribute is unfilled.

We can explore the idea where instead of storing an `-` value, we will not store anything onto the data xml file. When the field is empty (null), we will display - on the UI instead.

**Comment by awarenessxz** [comment]
I feel that instead of displaying a "-", why not just leave it blank? So we only displayed what was stored. 

After all, the fields are not labelled. So if the user sees a "-", they will not know if the "-" is referring to phone number / address / email / etc..
