### ISSUE TITLE
Comments on Display Photo Feature

### ISSUE THREAD

**Issue by awarenessxz** [CS2103AUG2017-W14-B2/main#31]
@wenzongteo 

I had a look at the initial display photo feature. So far, it is able to display a default no man picture or the user picture when added. It is a good starting point. 

I think for the next step, you might want to work on the delete part as the user's picture is not deleted from the storage after the user is being deleted.

**Comment by wenzongteo** [comment]
Hi bryan, thanks for your input! I have not thought about removal of photo in the situation that you have just mentioned.

Will aim to resolve this use case by next week!
